Restore `var vm` in `player.gd`
Fix problem when `tool` scripts try to refer `AutoLoad`s, which does
not work in Godot.

```
SCRIPT ERROR: GDScript::reload: Compile Error: Identifier not found: vm
   At: res://globals/player.gd:57.
ERROR: reload: Method/Function Failed, returning: ERR_COMPILATION_FAILED
   At: modules/gdscript/gdscript.cpp:598.
```

It appears to have been introduced in 7336e54bd30ca1b696085e2dc5fdb7e78e6c4d19
and easy to miss because export vars and such had been set before that
commit.